name: pyperformance (gil v.s. nogil 3.9.10)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        gil-version: [3.9.10]
        requirements-txt: ["requirements_pyperformance.txt"]
        benchmark-tasks: ["-sqlalchemy_declarative,-sqlalchemy_imperative"]
        output-path: ["/usr/src/app/output"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Python gil Docker image
      run: docker build . --file Dockerfile_gil --tag python-gil --build-arg REQUIREMENTS_FILE=${{ matrix.requirements-txt }}
    - name: Run Python gil pyperformance
      run: docker run -v $(pwd):${{ matrix.output-path }} python-gil python -m pyperformance run -o ${{ matrix.output-path }}/python-gil.json --benchmarks=${{ matrix.benchmark-tasks }}
    - name: Build the nogil 3.9.10 Docker image
      run: docker build . --file Dockerfile_nogil --tag python-nogil --build-arg REQUIREMENTS_FILE=${{ matrix.requirements-txt }}
    - name: Run nogil-3-9-10 pyperformance
      run: docker run -v $(pwd):${{ matrix.output-path }} python-nogil python -m pyperformance run -o ${{ matrix.output-path }}/python-nogil.json --benchmarks=${{ matrix.benchmark-tasks }}
    - name: Compare result
      run: docker run python-gil python -m pyperformance compare python-gil.json python-nogil.json
